### PR TITLE
Gradle 7.4+ Config Cache Support

### PR DESCRIPTION
**Pull request by chrisjenx**
Fix for: 
- https://github.com/gradle/common-custom-user-data-gradle-plugin/issues/10
- https://docs.gradle.org/7.4-rc-1/userguide/upgrading_version_7.html#for_use_at_configuration_time_deprecation

Changes to configuration cache means `forUseAtConfiguration()` are new deprecated, there is regression with the change that causes Gradle to detect the old way as changing input values when they don't, 7.4 will use the newer ways to match the config cache detection

### CODE REVIEW

**Comment by etiennestuder** [comment]
We will look into it once Gradle 7.4 final has been released.

**Comment by chrisjenx** [comment]
Bump

**Comment by etiennestuder** [comment]
We will get to it, as soon as we find time. You can always fork the plugin and host the plugin internally in the meantime.

**Comment by etiennestuder** [comment]
This cannot be merged since the commits by the contributor are not signed. I'll add the changes manually.

**Comment by etiennestuder** [comment]
Pushed to `main` via the following two commits.

image

**Comment by etiennestuder** [comment]
Thanks for the PR, @chrisjenx. We will publish a new release soon.

**Comment by chrisjenx** [comment]
What do you mean by not signed?

Also thanks!

**Pull request closed without merging**
